language: python
before_install:
- openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- ssh-keyscan -H $HOSTNAME >> ~/.ssh/known_hosts
install:
- pip install j2cli[yaml]
script:
- j2 ragnarok.rsc.j2 secrets.yml -o ragnarok.rsc
- scp -i $PRIVATE_KEY_FILE ragnarok.rsc $USERNAME@$HOSTNAME:/
- ssh -i $PRIVATE_KEY_FILE $USERNAME@$HOSTNAME import file=ragnarok.rsc
